### ISSUE TITLE
Can't download from http://tv.cctv.com/2017/11/28/VIDETRtb7usiG8XC3Om6ovxg171128.shtml

### ISSUE THREAD

**Issue by Yuren-Zhong** [cls1991/cntv-video-downloader#1]
I tried to download the video on http://tv.cctv.com/2017/11/28/VIDETRtb7usiG8XC3Om6ovxg171128.shtml, but it failed.

I found that `get_pid_by_url` returned `None`. It seems that the current URL doesn't match with the regular expressions of the assumed urls in your program.

Could you please take some time fix it? If you are busy, please instruct me how to fix this.

Thanks!

**Comment by cls1991** [comment]
Fixed!  @Yuren-Zhong

**Comment by Yuren-Zhong** [comment]
@cls1991 
this is the error output:

(cntv-downloader) D:\cntv-video-downloader>python main.py
****************************************
å¼€å§‹ä¸‹è½½è§†é¢‘
2017-11-30 17:57:41.499000
****************************************
æ­£åœ¨ä¸‹è½½ac09fcb6edab4904a27c30f93f31a16a_450_h264_418_aac_32.mp4
wget cmd: /usr/bin/wget --no-clobber -O ./tmp/ac09fcb6edab4904a27c30f93f31a16a_450_h264_418_aac_32.mp4 http://hot.v.cntv.cn/flash/mp4video62/TMS/2017/11/28/ac09fcb6edab4904a27c30f93f31a16a_450_h264_418_aac_32.mp4
The system cannot find the path specified.
****************************************
2017-11-30 17:57:41.826000
è§†é¢‘å…¨éƒ¨ä¸‹è½½å®Œæˆ
****************************************
å¼€å§‹åˆå¹¶åˆ†æ®µè§†é¢‘
Traceback (most recent call last):
  File "main.py", line 13, in <module>
    get_download_link(url, quality_type=5, get_dlink_only=False, is_merge=True, is_remain=False)
  File "D:\cntv-video-downloader\lib\cntv.py", line 57, in get_download_link
    download_videos(title + '.%s' % ext, dlinks=result, is_merge=is_merge, is_remain=is_remain)
  File "D:\cntv-video-downloader\lib\cntv.py", line 118, in download_videos
    merge_video(title)
  File "D:\cntv-video-downloader\lib\cntv.py", line 82, in merge_video
    print('ffmpeg cmd: %s' % cmd)
  File "C:\Users\v-yurzho\AppData\Local\conda\conda\envs\cntv-downloader\lib\encodings\cp1252.py", line 12, in encode
    return codecs.charmap_encode(input,errors,encoding_table)
UnicodeEncodeError: 'charmap' codec can't encode characters in position 81-82: character maps to <undefined>

**Comment by cls1991** [comment]
You don't install wget, ffmpeg tool on your windows system.
`url = 'http://tv.cctv.com/2017/11/28/VIDETRtb7usiG8XC3Om6ovxg171128.shtml'
    get_download_link(url, quality_type=5, get_dlink_only=False, is_merge=True, is_remain=False)`
Just set parameter get_dlink_only True,  to ignore the file downloading.

**Comment by Yuren-Zhong** [comment]
Thanks!

I got it right.
